---
  - name: "Configuring client node"
    hosts: [localhost]
    connection: local
    become: yes

    vars_prompt:
    - name: hostname
      prompt: "What is the hostname of this device?"
      private: false

    tasks:
      - import_tasks: tasks/update.yaml
      - import_tasks: tasks/install.yaml
      - import_tasks: tasks/hostname.yaml
      - import_tasks: tasks/services.yaml
      - import_tasks: tasks/filesystem.yaml