- name: "Changing hostname"
  hostname:
    name: 'pi-{{ clock }}'

- name: "Changing hostname in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1[ \t]+raspberrypi'
    line: '127.0.1.1                pi-{{ clock }}'
    state: present

- name: "Storing hostname in home directory"
  copy:
    src: /etc/hostname
    dest: "{{ lookup('env', 'HOME') }}/hostname.txt"
