- name: "Installing utilities"
  apt:
    name: "{{ utilities_APT }}"

- name: "Installing avahi"
  apt:
    name: "{{ avahi_APT }}"

- name: "Installing Python3 tooling"
  apt:
    name: "{{ python3_APT }}"
